// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NipeNikupe.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NipeNikupe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008072350_update_opot3")]
    partial class update_opot3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NipeNikupe.Models.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("counties", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mombasa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kwale"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kilifi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tana River"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lamu"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Taita-Taveta"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Garissa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Wajir"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mandera"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Marsabit"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Isiolo"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Meru"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tharaka-Nithi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Embu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Kitui"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Machakos"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Makueni"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Nyandarua"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Nyeri"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Kirinyaga"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Murang'a"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Kiambu"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Turkana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "West Pokot"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Samburu"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Trans-Nzoia"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Uasin Gishu"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Elgeyo-Marakwet"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Nandi"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Baringo"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Laikipia"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Nakuru"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Narok"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Kajiado"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Kericho"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Bomet"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Kakamega"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Vihiga"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Bungoma"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Busia"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Siaya"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Kisumu"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Homa Bay"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Migori"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Kisii"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Nyamira"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Nairobi"
                        });
                });

            modelBuilder.Entity("NipeNikupe.Models.SignUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("AvailableTime")
                        .HasColumnType("interval");

                    b.Property<string>("CityOrTown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalityOrArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("signUps", (string)null);
                });

            modelBuilder.Entity("NipeNikupe.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
